apiVersion: v2
name: yamtrack
description: A Helm chart for Yamtrack media tracker

type: application

version: 0.1.2

appVersion: "0.24.11"

dependencies:
  - name: postgresql
    version: "~16.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "~19.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
