{{- if .Values.certificates.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pocketbase.fullname" . }}-certs
  labels:
    {{- include "pocketbase.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $filename, $content := .Values.certificates.files }}
  {{ $filename }}: {{ $content | quote }}
  {{- end }}
{{- end }}
