{{- if .Values.imagePullSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\",\"email\":\"%s\"}}}" (printf "%s:%s" .Values.imagePullSecrets.ghcr.username .Values.imagePullSecrets.ghcr.password | b64enc) .Values.imagePullSecrets.ghcr.email | b64enc }}
{{- end }}
