apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http-frontend
      protocol: TCP
      name: http-frontend
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http-backend
  selector:
    app: {{ .Release.Name }}
