{{- if not .Values.yamtrack.existingSecret }}
{{- if or .Values.yamtrack.secret .Values.database.password (gt (len .Values.secretEnv) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yamtrack.fullname" . }}
  labels:
    {{- include "yamtrack.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.yamtrack.secret }}
  secret: {{ .Values.yamtrack.secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.password }}
  db-password: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key | lower | replace "_" "-" }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
